server {
  listen 8080;
  root /usr/share/nginx/html;
  index index.html;
  gzip on; gzip_types application/octet-stream application/json application/javascript text/css;
  gzip_static always; gunzip on;
  location ~ \.bin$ { default_type application/octet-stream; add_header Cache-Control "public, max-age=31536000, immutable"; }
  location ~ ^/(index\.html|sw\.js|manifest\.json)$ { add_header Cache-Control "no-cache"; }
  location / { try_files $uri $uri/ =404; }
}
